<link rel="stylesheet" href="../css/login.css">
<div class="wrapper">
    <form action="../controllers/login.php" method="POST">
        <h1 id="title">Sign in</h1>
        <div class="input-box">
            <input type="text" placeholder="e-mail" name="email" >
            <i class='bx bx-user'></i>
        </div>
        <div class="input-box">
            <input type="password" placeholder="password" name="password" >
            <i class='bx bx-lock'></i>
        </div>
        <div class="btn-container">
            <button class="btn" type="submit" name="login">Sign in</button>
        </div>
        <div class="register">
            <p>Don't have an account? <a href="../controllers/register.php">Register</a></p>
        </div>
        <?php if (!empty($wrongpass)) : ?>
            <div class="wrongpass"><?= $wrongpass ?></div>
        <?php endif; ?>
        <?php if (!empty($accinv)) : ?>
            <div class="accinv"><?= $accinv ?></div>
        <?php endif; ?>
        <?php if (!empty($chvide)) : ?>
            <div class="chvide"><?= $chvide ?></div>
        <?php endif; ?>
    </form>
</div>
