<link rel="stylesheet" href="../css/login.css">
<div class="wrapper">
    <form action="../controllers/register.php" method="POST">
        <h1 id="title">Sign up</h1>
        <div class="input-box">
            <input type="text" placeholder="e-mail" name="email" required>
            <i class='bx bxs-envelope'></i>
        </div>
        <div class="input-box">
            <input type="password" placeholder="password" name="password" required>
            <i class='bx bx-lock'></i>
        </div>
        <div class="input-box">
            <input type="password" placeholder="confirm password" name="cpassword" required>
            <i class='bx bx-repeat'></i>
        </div>
        <div class="btn-container">
            <button class="btn" type="submit" id="signin">Sign up</button>
        </div>
        <div class="register">
            <p>Already have an account? <a href="../controllers/login.php">Log in</a></p>
        </div>
        <?php if (!empty($pwderror)) : ?>
            <div class="pwderror"><?= $pwderror ?></div>
        <?php endif; ?>
        <?php if (!empty($emailexist)) : ?>
            <div class="emailexist"><?= $emailexist ?></div>
        <?php endif; ?>
        <?php if (!empty($regsucc)) : ?>
            <div class="regsucc"><?= $regsucc ?></div>
        <?php endif; ?>
        <?php if (!empty($regerror)) : ?>
            <div class="regerror"><?= $regerror ?></div>
        <?php endif; ?>
    </form>
</div>
